### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by victorstewart** [amdn/itoa#1]
Hey there,

I just tried compiling the code and got some errors? I'm probably doing something wrong.. thanks for taking a look!

with this command : 

g++ -std=c++1y -g -Wall -o itoa itoa.cpp itoa.h itoa_impl.h

got:
                                         ^
itoa_impl.h:207:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_t<not std::is_signed<U>::value
                  ^
itoa_impl.h:207:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_t<not std::is_signed<U>::value
                             ^
itoa_impl.h:216:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_tstd::is_signed<I::value
                  ^
itoa_impl.h:216:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_tstd::is_signed<I::value
                             ^
itoa.cpp:31:53: error: ‘std::index_sequence’ has not been declared
     constexpr auto generate_array( Gen&& item, std::index_sequence<Is...>)
                                                     ^
itoa.cpp:31:67: error: expected ‘,’ or ‘...’ before ‘<’ token
     constexpr auto generate_array( Gen&& item, std::index_sequence<Is...>)
                                                                   ^
itoa.cpp:37:12: error: ‘make_index_sequence’ is not a member of ‘std’
         }, std::make_index_sequence<200>{} );
            ^
itoa.cpp:37:41: error: expected primary-expression before ‘{’ token
         }, std::make_index_sequence<200>{} );
                                         ^
In file included from itoa.h:28:0:
itoa_impl.h:207:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_t<not std::is_signed<U>::value
                  ^
itoa_impl.h:207:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_t<not std::is_signed<U>::value
                             ^
itoa_impl.h:216:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_tstd::is_signed<I::value
                  ^
itoa_impl.h:216:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_tstd::is_signed<I::value
                             ^
itoa_impl.h:207:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_t<not std::is_signed<U>::value
                  ^
itoa_impl.h:207:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_t<not std::is_signed<U>::value
                             ^
itoa_impl.h:216:18: error: ‘std::enable_if_t’ has not been declared
             std::enable_if_tstd::is_signed<I::value
                  ^
itoa_impl.h:216:29: error: expected ‘>’ before ‘<’ token
             std::enable_if_tstd::is_signed<I::value
                             ^

**Comment by amdn** [comment]
Hi Victor,

Looks like that's an older version of g++ that doesn't support c++14
features like std::enable_if_t.

Art

**Comment by victorstewart** [comment]
Thanks Art! I'll upgrade it. By the way, is this faster than sse2 on https://github.com/miloyip/itoa-benchmark ? I saw you had contributed there, but didn't see this implementation on there.

**Comment by amdn** [comment]
It is faster on a Skylake processor for most of the 8 benchmarks.  I
haven't contributed it to Milo's benchmark because it uses premake instead
of cmake and it would need to be configured for C++14, and I didn't want to
take the time to learn premake.

**Comment by victorstewart** [comment]
awesome! well thank you again
