### ISSUE TITLE
please check this one, it's faster than yours

### ISSUE THREAD

**Issue by michaelqxd** [amdn/itoa#2]
itoa-benchmark
https://github.com/miloyip/itoa-benchmark

**Comment by amdn** [comment]
Which compiler did you use, and what optimization level? Using g++ version 6.2 I get consistently faster results for https://github.com/amdn/itoa than for https://github.com/amdn/itoa_ljust (which is   the fastest of the algorithms in https://github.com/miloyip/itoa-benchmark).

**Comment by amdn** [comment]
Cannot reproduce claim, please give me more information if you'd like for me to look at this further.
